import { writeFile } from 'node:fs/promises'
import { getBuiltinModels, getBuiltinProviders } from '@earendil-works/pi-ai/providers/all'

const models = getBuiltinProviders().flatMap(provider =>
  getBuiltinModels(provider).map(model => ({
    provider: model.provider,
    id: model.id,
    name: model.name,
    api: model.api,
    contextWindow: model.contextWindow,
    maxTokens: model.maxTokens,
    reasoning: model.reasoning,
    input: model.input,
  })),
)

const source = `/* Generated by scripts/generate-catalog.mjs. */\nimport type { OfficialModelSummary } from './types.ts'\n\nexport const OFFICIAL_MODELS: readonly OfficialModelSummary[] = ${JSON.stringify(models, null, 2)}\n`
await writeFile(new URL('../src/shared/catalog.generated.ts', import.meta.url), source)
